name: objectbox_benchmark
description: Simple ObjectBox-Dart performance benchmark
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  objectbox: any
  meta: ^1.3.0

dev_dependencies:
  lints: ^2.0.1
  objectbox_generator: any
  build_runner: any

dependency_overrides:
  objectbox:
    path: ../objectbox
  objectbox_generator:
    path: ../generator
