name: objectbox
version: 0.4.0-dev.2
repository: https://github.com/objectbox/objectbox-dart
homepage: https://objectbox.io
author: objectbox.io
description: ObjectBox is a super-fast NoSQL ACID compliant object database.

environment:
  sdk: '>=2.5.0 <2.6.0'

dependencies:
  flat_buffers: 1.11.0 # take care updating flatbuffers - keep aligned with other bindings
  ffi: 0.1.2

dev_dependencies:
  build_runner: ^1.0.0
  objectbox_generator:
    path: generator
  pedantic: ^1.8.0+1
  test: ^1.0.0
