name: objectbox
version: 0.8.1
repository: https://github.com/objectbox/objectbox-dart
homepage: https://objectbox.io
description: ObjectBox is a super-fast NoSQL ACID compliant object database.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  # take care updating flatbuffers - keep aligned with other bindings
  flat_buffers: 1.12.0
  ffi: ^0.1.3

dev_dependencies:
  build_runner: ^1.0.0
  objectbox_generator:
    path: generator
  pedantic: ^1.9.0
  test: ^1.0.0
