name: objectbox_demo
description: An example project for the objectbox-dart binding.
version: 0.3.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  path_provider: any
  intl: any
  objectbox: ^0.8.1
  objectbox_flutter_libs: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  objectbox_generator: ^0.8.1

flutter:
  uses-material-design: true

# Note: these overrides are only for ObjectBox internal development, don't use them in your app.
dependency_overrides:
  objectbox:
    path: ../../..
  objectbox_generator:
    path: ../../../generator
  objectbox_flutter_libs:
    path: ../../../flutter_libs