name: vectorsearch_cities
description: Vector Search Example with Cities.
version: 1.0.0

environment:
  sdk: ^2.18.6

dependencies:
  objectbox: ^4.0.2

dev_dependencies:
  build_runner: ^2.4.9
  lints: ^3.0.0
  objectbox_generator: any

# Note: these overrides are only for ObjectBox internal development, don't use them in your app.
dependency_overrides:
  objectbox:
    path: ../../../../objectbox
  objectbox_generator:
    path: ../../../../generator
