name: objectbox_model_generator
version: 0.3.0
description: >-
  A preprocessor for Dart source files containing ObjectBox entity definitions.
environment:
  sdk: '>=2.5.0-dev.2.0 <3.0.0'
dependencies:
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  objectbox:
    path: ../..
dev_dependencies:
  build_runner: '>=0.9.0 <0.11.0'
