name: Close inactive issues
on:
  schedule:
    - cron: "20 1 * * *" # “At 01:20.” Avoid using top of the hour to reduce load on GitHub.
  workflow_dispatch: # To support running manually.

# Minimal access by default
permissions:
  contents: read

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      issues: write
      pull-requests: write
    steps:
      # https://github.com/marketplace/actions/close-stale-issues
      - uses: actions/stale@997185467fa4f803885201cee163a9f38240193d # v10.1.1
        with:
          days-before-stale: -1 # Add the stale label manually.
          days-before-close: 21
          only-labels: "more info required"
          stale-issue-label: "more info required"
          close-issue-message: "Without additional information, we are unfortunately not sure how to resolve this issue. Therefore this issue has been automatically closed. Feel free to comment with additional details and we can re-open this issue."
          close-pr-message: "Without additional information, we are unfortunately not sure how to address this pull request. Therefore this pull request has been automatically closed. Feel free to comment with additional details or submit a new pull request."
